---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: WG-Easy_VPN
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LANG=es
      - PASSWORD=${WG_PASSWORD}
      - WG_HOST=${WG_HOST}
      - WG_PORT=51820
      - WG_DEFAULT_DNS=${FTLCONF_LOCAL_IPV4}
      - WG_DEFAULT_ADDRESS=100.64.0.x 
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0 
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./wireguard:/etc/wireguard
